### ISSUE TITLE
Error: Stream yields empty buffer

### ISSUE THREAD

**Issue by M493** [GrumpyPirate/Sphaxify#5]
When I use _MakePacks.bat, I run into the following error:
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: Stream yields empty buffer
    at Socket.<anonymous> (C:\Users\9thha\Desktop\Minecraft devving\Sphaxify-1.2.1\node_modules\gm\lib\command.js:57:17)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

The folder structure from source files is duplicated in packs as expected, but with no image files. I wish I had more than the faintest idea of how to help further. Please let me know if you want me to try anything out to track it down.

**Comment by M493** [comment]
Update: I went through the Node, ImageMagick, and GraphicsMagick steps and updated them, and now I have no issues. My versions were just over a year out of date!
